//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderProduct
    {
        public int OrderId { get; set; }
        public int SellerProductId { get; set; }
        public int BuyerId { get; set; }
        public int Quantity { get; set; }
        public Nullable<bool> IsVisible { get; set; }
        public int TransactionId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual UserTable UserTable { get; set; }
        public virtual SellerProduct SellerProduct { get; set; }
        public virtual Transaction Transaction { get; set; }
    }
}
