//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellerProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SellerProduct()
        {
            this.OrderProducts = new HashSet<OrderProduct>();
        }
    
        public int SellerProductId { get; set; }
        public decimal ProductPrice { get; set; }
        public decimal ShippingPrice { get; set; }
        public int CountryId { get; set; }
        public int SellerId { get; set; }
        public int ProductId { get; set; }
        public int TotalNumber { get; set; }
    
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProduct> OrderProducts { get; set; }
        public virtual Product Product { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
